name: MLOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install -r reqs.txt

      - name: Train model
        run: |
          python train.py
